[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
vector2d = "1"
strum = "0.24.1"
strum_macros = "0.24.1"
maplit = "1.0.2"
num-bigint = "0.4.3"